# Generated by Django 5.1.7 on 2025-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='buyer_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='seller_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
