# Generated by Django 5.1.6 on 2025-05-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
