# Generated by Django 5.2 on 2025-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_devicenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
