# Generated by Django 5.1.6 on 2025-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('computers', 'Computers'), ('televisions', 'Televisions'), ('projectors', 'Projectors'), ('printers', 'Printers'), ('cameras', 'Cameras'), ('speakers', 'Speakers')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
